"""create table Food

Revision ID: 22cc26bd79e8
Revises: 
Create Date: 2022-02-05 20:51:12.057704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cc26bd79e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first1', sa.String(), nullable=False),
    sa.Column('first2', sa.String(), nullable=False),
    sa.Column('second1', sa.String(), nullable=False),
    sa.Column('second2', sa.String(), nullable=False),
    sa.Column('third1', sa.String(), nullable=False),
    sa.Column('third2', sa.String(), nullable=False),
    sa.Column('snack1', sa.String(), nullable=False),
    sa.Column('snack2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    # ### end Alembic commands ###
